### PR TITLE
Add stream documentation.

### PR DESCRIPTION
**Pull request by explorigin**
Address #189

### CODE REVIEW

**Comment by leeoniya** [comment]
neat.

> One limitation of passing streams as the element body is that it is incompatible with `defineElementSpread`.

this seems like a silly limitation. there's no good reason for it to exist. want to do another PR to address this? it's basically just another `||` condition here [1]. just make sure gate it on FEAT_STREAM, similar to [2]. Speaking of [2], as you can see, CSS values also support streams. I would also like streams to be documented after `Autoredraw`, since they're naturally a way of addressing the same issue.

thanks!

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/addons/defineElementSpread.js#L17
[2] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/patchStyle.js#L18-L21

**Comment by leeoniya** [comment]
another important thing to mention is that streams should never return vnodes generated by domvm's factory methods. since streams will return their cached values until they change, it *will* cause undefined behavior and probably memory leaks, since vnodes should never be reused in app-space.

**Comment by leeoniya** [comment]
i've pushed the needed changes to support streams in `defineElementSpread`: https://github.com/leeoniya/domvm/commit/1e235746f95a31cf7ddde6f21b0f021bb8d486ba

**Comment by leeoniya** [comment]
hey @explorigin thanks for this PR, i've added some stream docs in a slightly different format here: https://github.com/leeoniya/domvm#streams

**Comment by explorigin** [comment]
Thanks, I'm glad to see some documentation in there.  If you're interested, you can see how I'm using domvm [here](https://github.com/explorigin/portfolio/tree/master/packages/gallery/src/interface).

**Pull request closed without merging**
