### PR TITLE
IE8 support

### PR DESCRIPTION
**Pull request by e1ectronic**
Small changes to make DOMVM compatible with the Internet Explorer 8.

### CODE REVIEW

**Comment by leeoniya** [comment]
hey @e1ectronic thanks for the update.

Booting up a Win7/IE8 VirtualBox VM and trying to run the tests in IE8 produces a wall of console errors that prevent QUnit from loading at all due to missing `Object.defineProperty`. I figured maybe i'd throw in https://github.com/es-shims/es5-shim and be done with it, but the problem seems to go much deeper [1]. `Object.defineProperty` is also used extensively by another critical component of the testing framework [2].

Unfortunately, the inability to run the test suite even in a polyfilled environment is a show-stopper for official inclusion, since we have 0 knowledge about how much is actually broken.  Even if we roll QUnit back to a version that supported IE8, you would still not be able to have any kind of mutation observation that DOMInstr provides in IE9+ and is a requirement for test soundness.

It's somewhat disappointing that this work cannot be merged without major changes to the testing infrastructure. At minimum, I hope that my advice has helped you extract the minimum required changes needed in domvm to support your specific app.

Let's be honest though, it's 2017 and IE8 is long dead [3]. Even on XP, users have several good options of modern-ish browsers that will all work 100x better than any IE version. Just browsing the current web in IE8 on the VM was completely broken for me on most major websites. It's time to move on.

[1] https://github.com/qunitjs/qunit/issues/1031
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/test/dominstr.js
[3] https://github.com/webpack/webpack/issues/3070

**Comment by lawrence-dol** [comment]
> Let's be honest though, it's 2017 and IE8 is long dead ...

Yes it is; even we, a long-tail-support-everything-ancient shop, have moved on to modern browsers. Actually, the death of the Java applet has helped us there.

Besides, as the WannaCrypt worm has reminded us, running out of support O/S versions is a really bad idea.

**Comment by e1ectronic** [comment]
My main compatibility problem with IE8 is not related to websites, but to [HTML applications](https://en.wikipedia.org/wiki/HTML_Application) running on Windows XP and later.

I know that [Electron](https://electron.atom.io/) is a better choice of framework for application development with Javascript, but as a result executables are just too big for small tasks such as creating Excel price list from MS SQL database with some custom columns. By the way, I'm not sure whether Electron supports MS Office automation via ActiveX at all.

OK... If you are not interesting in IE8 changes, I can continue using my custom DOMVM builds until Windows XP computers finally disappear from the office.

**Comment by leeoniya** [comment]
i'm only opposed to merging changes that cannot be tested for regressions between commits. simply because *your* app happens to work in IE8 *today* doesn't mean that if you make a minor code change tomorrow that won't hit a major bug that we simply didnt know never worked to begin with since no tests could ever be run against IE8.

if there was any guarantee that 100% of existing tests pass in IE8 today, then i would be more comfortable knowing that at least these minimal changes are the full surface area needed for reliable IE8 support (modulo new features...which are coming). keep in mind that even the coverage of the current 500+ assertions is likely only 30-40% of the codebase. some more is maybe covered by the demo apps that i test manually and some would definitely be broken in ie8 even with your prior fixups.

i will keep the ie8 branch around in the main repo w/this commit to make sure the work doesn't go to waste.

> I know that Electron is a better choice of framework for application development with Javascript, but as a result executables are just too big for small tasks such as creating Excel price list from MS SQL database with some custom columns.

You may want to consider simply running a local HTTP server using the much smaller [and portable] node binaries [1] & some minimal npm modules w/ your scripts rather than using the entire Electron framework which re-distributes all of Blink/Chromium in addition to node for every app you make. I actually do this for a lot of stuff and simply use an already-running local browser as the UI.

[1] https://nodejs.org/en/download/

**Comment by reviewher** [comment]
@leeoniya according to http://qunitjs.com/ :

> For legacy browser support, including Internet Explorer versions lower than IE9, please use the 1.x series of QUnit.

Would the tests work if you just rolled back QUnit?

**Comment by leeoniya** [comment]
as mentioned, `DOMInstr` uses `Object.defineProperty` as a core mechanism for instrumenting the DOM api to track and count DOM ops. almost every test has an expected dom op count. even if we rolled back qunit, then we may have to strip out the dom op expectations from all the tests and drop DOMInstr at which point we would have ie8-specific tests.

*if* anyone is willing to do all of that and get all *those* tests passing in ie8, then we can say "yes, ie8 is probably fine". i would keep those tests and the qunit downgeade in a separate ie8 branch because i am not willing to strip everything down for the sake of an ie8 lowest common denominator.

i certainly dont have the time nor desire to go through this effort for a browser i've tried very hard to forget.

**Comment by lawrence-dol** [comment]
> i certainly dont have the time nor desire to go through this effort for a browser i've tried very hard to forget.

And forgotten it should be. Supporting IE8 in 2017 just doesn't make sense.

**Comment by leeoniya** [comment]
@e1ectronic i'm going to close this. ping me if you ever get around to getting all tests passing in ie8 without the DOM op expectations.

thanks for this ie8 work, it now lives in the ie8 branch.

**Pull request closed without merging**
