### PR TITLE
manage `checked` and `value` properties of INPUT elements

### PR DESCRIPTION
**Pull request by yosbelms**
### Motivation
The first time a `input` element is rendered with a initial value for `checked` attributes it sets `checked` property with that value, if the `checked` attribute is changed dinamically the property does no change, so it would looks like doesn't works, because `chacked` attribute belongs to `defaultChecked` property, hence you can not trust `vm.node.el.checked`. The same issue with `value`.

This PR solves that problem. So now you can savely do:
```
['input', {type; 'checkbox', checked: isChecked}]
```

### CODE REVIEW

**Comment by yosbelms** [comment]
3b4d8c0 now pass all tests and add `selected` attribute

**Comment by leeoniya** [comment]
@yosbelms 

before i merge this, can you create several tests that fail before these changes but pass afterwards? i would prefer to apply the commits in <failing tests> => <fix patches> order. in addition, please make sure to check tge dbmonster bench to ensure there are no obvious perf regressions after the changes.

there are already bool attr tests for `checked`. you can put the new ones in close proximity to the others.

thanks!

**Comment by yosbelms** [comment]
@leeoniya this patch breaks some bad written tests (44, 45, 46, 47) so, you will need to rewrite it.

**Comment by leeoniya** [comment]
Could you clarify what you mean by "some bad written tests"?

In domvm there is currently no cross-setting of props and attrs. `{".checked": true}` sets and diffs the prop while `{checked: true}` sets and diffs the attribute.

What this patch does is conflate them, which is okay because the DOM does this shit to us. And it's on my todo to get this properly handled.

However, we need to be very specific about *exactly* how and when they intermix. This single test shows how to fix one specific case but is very insufficient in demonstrating that the problem is solved generally and in a uniform fashion. This issue goes much deeper and touches event handler interaction as well, in the `watch` module with regards to `watch.sync`, etc. If you want to have a workable TodoMVC before a full solution and many tests are in place, just use ".checked", ".value", etc. You will lose the attributes but your DOM and model should at least stay in sync.

Maybe it'll be simpler in the end than I imagine. All I know is that there are far too few tests to ensure the correct, intentionally engineered behavior happens in all cases.

So let's discuss...

Can we assume that the prop is always correct? Probably.

Should domvm incur the overhead of always keeping the attribute in sync with the prop even if the templates do not explicitly ask for this? Should it be a config opt-in? Or opt-out?

My initial gut feeling says that the overhead is worth the uniformity and we should simply always set the matching attributes. However, what if someone wants to do a `form.reset()`? Does the DOM use the attributes to keep state of the original values? I don't know yet.

All of these things and likely many more need to be decided before beginning to mix props and attrs.

**Comment by jbucaran** [comment]
@leeoniya Can you clarify the action taken here?

I'm facing a similar issue right now and from what I can see in the code you decided to sync props with attrs only for _dynamic props_. 👋

**Comment by leeoniya** [comment]
so the idea of all vdom is to sync the real dom to the current vtree, which is built from some current state. normally, user actions do not directly modify the dom, so it is up to the vdom lib to do this. with some dom elements - like form inputs - the dom is directly mutated by user input without and in fact explicitly setting it again will reset selection range or cursor position or focus. lets say you render a text input `value="1"` and an oninput handler that syncs the value into the current state. then the user enters "2" so value becomes "12" and the dom *also* becomes "12" before any redraw is called. so now you have:

old vtree: 1
new vtree: 12
dom: 12 (focused with cursor at end)

during patching, you should not set the value to "12" because focus would be lost (and maybe undo history). to avoid setting it, you diff against the actual live value in the dom rather than the old vtree.

the user is still required to sync the live value into the app state so the new vtree is correct for diffong with the live dom, but the patching process has to avoid setting it again.

domvm does not keep the dynamic attrs in sync with the props, it just sets the props directly and lets the attrs maintain the original values (same as html)

looking at it again, i'm not certain avoiding resetting is really necessary for "checked", "selected",  or "selectedIndex" it's an optimization that may actually have negative overall impact since it incurs overhead of testing every attr against that switch..which is already why the tag switch disabled there.

will need to look at this again tmrw.

hope that helps!

**Comment by jbucaran** [comment]
Thank you as usual @leeoniya! 🙏

**Pull request closed without merging**
