### PR TITLE
add didEnter and didExit events to the router config

### PR DESCRIPTION
**Pull request by yosbelms**
docs included

### CODE REVIEW

**Comment by leeoniya** [comment]
thanks 👍

**Comment by yosbelms** [comment]
Opps! you merged fast, I was planning to put a little more work on it, example, prevent the execution of `didEnter` if `false` is returned in `onenter` to be compliant with `willEnter->onenter` flow.

**Comment by leeoniya** [comment]
regarding that topic, i've been concerned that the concept of callback prevention is somewhat fragile. it works well when the user interacts with your app, but would cause unexpected things if they directly access a route via bookmark or direct addressbar input. on theory, the nav should be reverted automatically but it would be unexpected to have a route entered into the address bar and the callback be prevented.

thhoughts?

**Comment by lawrence-dol** [comment]
> i've been concerned that the concept of callback prevention is somewhat fragile

I agree, provided the reason isn't because the route change was prevented. Otherwise, if the callback chooses to behave differently under some circumstances, that should be entirely an application concern and DOMVM doesn't want to be involved in it.

**Comment by yosbelms** [comment]
Actually `willEnter` can prevent `onenter`, so `onenter` should prevent `didEnter` to standarize the events flow. In other way all prevention could be removed.

> works well when the user interacts with your app, but would cause unexpected things if they directly access....

Because that, the routing logic must be stateless, and the ability to construct the entire page should be assigned to the view.

**Comment by leeoniya** [comment]
> Actually willEnter can prevent onenter, so onenter should prevent didEnter to standarize the events flow.

I think that only `willEnter` and `willExit` should be able to prevent further routing and must be responsible for any nav reversion and redirecting. `onenter` is meant to be reactive and is married to `didEnter` (which is just a DRY helper). same goes for `onexit`/`didExit`. Being able to prevent the DRY helpers from already-invoked route handlers that signify successful entry/exit would make things confusing.

following this reasoning, it means removing the existing `false` return handling for `onenter` and `onexit`. moreover, this only prevented the actual addressbar/history from getting set. this handling was never documented, so I'm okay with removing it. in addition, it was present at first before router-wide `willEnter` and `willExit` existed, so was not doable another way.

**Pull request merged**
